version: "3.8"

services: 
  core:
    container_name: mmdetection_test_core
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build: 
      context: ../../
      dockerfile: environments/development/Dockerfile-core
      # args:
        # PYTHON_VERSION: 3.6
        # APPLICATION_DIRECTORY: /mmdetection_test
    shm_size: 24G
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ../../../mmdetection_test:/home/gatheluck/code
      - ../../../detection_data:/volume/detection_data