FROM nvidia/cuda:11.0-devel-ubuntu20.04
SHELL ["/bin/bash", "-c"]

ARG PYTHON_VERSION
ARG APPLICATION_DIRECTORY
ARG USER_NAME=default

# Without following setting, decoding error will be raised
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
# Restrict python log
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONPATH ${APPLICATION_DIRECTORY}

# Following is needed to install python 3.6, 3.9
RUN apt update && apt install --no-install-recommends -y software-properties-common 
RUN add-apt-repository ppa:deadsnakes/ppa

# Last line is needed for MM Detection 
RUN apt update && apt install --no-install-recommends -y \
    git curl ssh openssh-client \
    python${PYTHON_VERSION} python3-dev python3-pip python-is-python3 \
    python${PYTHON_VERSION}-dev build-essential libgl1-mesa-dev
    
# Following is needed to swtich default python3 version
# For detail, please check following link
# https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1 \
    && update-alternatives --set python3 /usr/bin/python${PYTHON_VERSION} \
    && pip3 install poetry

# Add user. Without this, following process is executed as admin (This will lead file permission problem.). 
RUN useradd -ms /bin/sh ${USER_NAME}
USER ${USER_NAME}

WORKDIR ${APPLICATION_DIRECTORY}