defaults:
  - detector: yolov3
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

device: cuda
checkpoint_path: models/${detector.checkpoint_name}
mmdet_config_path: src/config/mmdetection/${detector.mmdet_config_relative_path}
input_image_dir: null
