version: "3.8"

services: 
  mmdetection_test:
    container_name: mmdetection_test_continuous_integration
    build: 
      context: ../../
      dockerfile: environments/development/Dockerfile-core
      shm_size: 12G
      args:
        PYTHON_VERSION: 3.6
        APPLICATION_DIRECTORY: /mmdetection_test
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    user: 1000:1000
    volumes:
      - ../../../MMDetectionTest:/mmdetection_test